export const bookData = [
    {
        id:1,
        img:'/assets/ScienceBooks/scienceBook1.jpg',
        title:'A Brief History of Time ',
        author:'Stephen Hawking',
        type:'Non-Fiction',
        description:'This classic book explores the mysteries of the universe, including black holes, time travel, and the Big Bang, in a way that is accessible to general readers.',
    },
    {
        id:2,
        img:'/assets/ScienceBooks/scienceBook2.jpg',
        title:'The Selfish Gene',
        author:'Richard Dawkins',
        type:'fantacy',
        description:'Dawkins introduces the concept of the "selfish gene," explaining how genes drive evolution and behavior. The book is known for its clear explanation of complex biological ideas',
    },{
        id:3,
        img:'/assets/ScienceBooks/scienceBook3.jpg',
        title:'The Elegant Universe',
        author:'Brian Greene',
        type:'Non-Fiction',
        description:'This book delves into the world of string theory, a cutting-edge idea in physics that attempts to unify all fundamental forces of the universe. Greene makes complex concepts understandable and fascinating.',
    },{
        id:4,
        img:'/assets/ScienceBooks/scienceBook4.jpg',
        title:'Sapiens',
        author:'Yuval Noah Harari',
        type:'Science',
        description:'Harari explores the history of humanity, from the evolution of Homo sapiens to the modern world, blending science, history',
    },{
        id:5,
        img:'/assets/ScienceBooks/scienceBook5.jpg',
        title:'The Gene',
        author:'Siddhartha Mukherjee',
        type:'Non-Fiction',
        description:'Harari explores the history of humanity, from the evolution of Homo sapiens to the modern world, blending science, history',
    },
    {
        id:6,
        img:'/assets/ScienceBooks/scienceBook1.jpg',
        title:'A Brief History of Time ',
        author:'Stephen Hawking',
        type:'fiction',
        description:'This classic book explores the mysteries of the universe, including black holes, time travel, and the Big Bang, in a way that is accessible to general readers.',
    },
    {
        id:7,
        img:'/assets/ScienceBooks/scienceBook2.jpg',
        title:'The Selfish Gene',
        author:'Richard Dawkins',
        type:'crime',
        description:'Dawkins introduces the concept of the "selfish gene," explaining how genes drive evolution and behavior. The book is known for its clear explanation of complex biological ideas',
    },{
        id:8,
        img:'/assets/ScienceBooks/scienceBook3.jpg',
        title:'The Elegant Universe',
        author:'Brian Greene',
        type:'crime',
        description:'This book delves into the world of string theory, a cutting-edge idea in physics that attempts to unify all fundamental forces of the universe. Greene makes complex concepts understandable and fascinating.',
    },{
        id:9,
        img:'/assets/ScienceBooks/scienceBook4.jpg',
        title:'Sapiens',
        author:'Yuval Noah Harari',
        type:'fantacy',
        description:'Harari explores the history of humanity, from the evolution of Homo sapiens to the modern world, blending science, history',
    },{
        id:10,
        img:'/assets/ScienceBooks/scienceBook5.jpg',
        title:'The Gene',
        author:'Siddhartha Mukherjee',
        type:'fantacy',
        description:'Harari explores the history of humanity, from the evolution of Homo sapiens to the modern world, blending science, history',
    }
]